## basics

In [3]:
x = 5
y = 'hello'
z = 5.2
type(x) , type(y) , type(z)

(int, str, float)

In [4]:
5 / 2 , 5 // 2 , 3 ** 2  # division , power

(2.5, 2, 9)

In [5]:
x.__add__(2), x.bit_count(), x.bit_length(), x.__bool__(), x.__xor__(5)

(7, 2, 3, True, 0)

In [6]:
y.capitalize(), y.casefold(), y.count('h'), y.find('e'), y.endswith('o'), y.isalpha(), 'e' in y, 'e' not in y, y.__len__(), len(y)

('Hello', 'hello', 1, 1, True, True, True, False, 5, 5)

## collections

In [7]:
li = ['apple', 'banana', 'cherry']
li[1] = 'mango'
li.insert(3,'blackberry')
li.append('banana')
li.sort()
len(li), li[1], li[2:5], li

(5,
 'banana',
 ['blackberry', 'cherry', 'mango'],
 ['apple', 'banana', 'blackberry', 'cherry', 'mango'])

In [8]:
li.reverse()
li

['mango', 'cherry', 'blackberry', 'banana', 'apple']

In [9]:
t = ('apple', 'banana', 'cherry')
t.count('banana'), t.index('apple'), t.__len__()

(1, 0, 3)

In [10]:
s = {'apple', 'banana', 'cherry'}
s.add('barry')
print(s)

{'barry', 'cherry', 'banana', 'apple'}


## numpy

In [11]:
import numpy as np

In [12]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [13]:
np.__version__

'1.26.1'

In [14]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr.ndim

2

In [16]:
arr[::2]

array([[1, 2, 3]])

In [17]:
arr = np.array([1,2,3], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3']
|S1


In [18]:
arr2 = arr.copy()
arr3 = arr.view()

In [19]:
arr.base, arr2.base, arr3.base

(None, None, array([b'1', b'2', b'3'], dtype='|S1'))

In [20]:
print(arr.T)

[b'1' b'2' b'3']


In [21]:
np.split(arr,3,0)

[array([b'1'], dtype='|S1'),
 array([b'2'], dtype='|S1'),
 array([b'3'], dtype='|S1')]

In [22]:
np.sort(arr)

array([b'1', b'2', b'3'], dtype='|S1')

In [23]:
fi = arr != '1'
arr[fi]

array([b'1', b'2', b'3'], dtype='|S1')

In [24]:
np.stack((arr,arr))

array([[b'1', b'2', b'3'],
       [b'1', b'2', b'3']], dtype='|S1')

In [25]:
from sklearn.feature_extraction.text import CountVectorizer

In [26]:
f = open("text file.txt", 'r')
text = f.read()
text.rstrip()
text.lstrip()
text

'summer is here.\nsky is bright.\nbirds are gone.\nnests are empty.\nwhere is the rain?'

In [27]:
s = text.split('\n')
s

['summer is here.',
 'sky is bright.',
 'birds are gone.',
 'nests are empty.',
 'where is the rain?']

In [33]:
vectorizer = CountVectorizer()
vector = vectorizer.fit_transform(s)
vectorizer.vocabulary_

{'summer': 10,
 'is': 6,
 'here': 5,
 'sky': 9,
 'bright': 2,
 'birds': 1,
 'are': 0,
 'gone': 4,
 'nests': 7,
 'empty': 3,
 'where': 12,
 'the': 11,
 'rain': 8}

In [34]:
vector.toarray()

array([[0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0],
       [1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1]], dtype=int64)

In [35]:
from scipy.spatial.distance import cosine

In [41]:
def cosine_dis(s1, s2):
    s = [s1, s2]
    vectorizer = CountVectorizer()
    vector = vectorizer.fit_transform(s)
    arr = vector.toarray()
    v1 = arr[0].tolist()
    v2 = arr[1].tolist()
    dis = cosine(v1, v2)
    return (1 - dis) * 100

In [43]:
cosine_dis("i like apple", "i love apple")

50.0

In [44]:
def cosine_dis_multi(s):
    vectorizer = CountVectorizer()
    victors = vectorizer.fit_transform(s)
    arr = victors.toarray()
    distances = []
    for i in range(len(s)):
        for j in range(i+1, len(s)):
            distances.append(cosine(arr[i], arr[j]))
    return distances

In [45]:
cosine_dis_multi(['i like tea', 'i love tea', 'i drink tea'])

[0.5, 0.5, 0.5]

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
model = TfidfVectorizer()
model.fit_transform()